name: AqCrates
main: gg.aquatic.crates.CratesPlugin
version: ${version}
api-version: 1.21
folia-supported: true

dependencies:
  server:
    Waves:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false